config/routes.rb
Rails.application.routes.draw do

  resources :hons, only: [:index, :create, :edit, :show, :update, :destroy]

  get 'about' => 'hons#about', as: 'about'
  get 'yuzas' => 'hons#yuzas', as: 'yuzas'
  get 'kansougun' => 'hons#kansougun', as: 'kansougun'

  root 'hons#top'
  
  devise_for :yuzas
  resources :yuzas, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hon.rb
class Hon < ApplicationRecord
    validates :title, presence: true
    validates :kansou, presence: true
    validates :kansou, length: { maximum: 200 }

    belongs_to :yuza
end

app/models/yuza.rb
class Yuza < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: { in: 2..20 }
  validates :yuza_jikosyo, length: { maximum: 50 }

  has_many :hons

  attachment :yuza_gazou
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_yuza!, except: [:top, :about]
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  # ログインしたらマイページに飛ばす
  def after_sign_in_path_for(resource)
    yuza_path(current_yuza.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/hons_controller.rb
class HonsController < ApplicationController
  def index
    @hons = Hon.all
    @hon = Hon.new
    @yuza = current_yuza
  end

  def show
    @hon = Hon.find(params[:id])
  end

  def create
    @hons = Hon.all
    @yuza = current_yuza
    @hon = Hon.new(hon_params)
    @hon.yuza_id = current_yuza.id
    if @hon.save
      redirect_to hons_path, notice:'投稿成功！こんぐらちゅれーしょん！'
    else
      render :index
    end
  end

  def edit
    @hon = Hon.find(params[:id])
    if @hon.yuza != current_yuza
      redirect_to hons_path, notice:'＜error＞投稿者以外は編集することができません'      
    end
  end

  def update
    hon = Hon.find(params[:id])
    if hon.update(hon_params)
      redirect_to hon_path(hon), notice:'編集成功っす'
    else
      redirect_to hon_path(hon), notice:'編集できませんでした。タイトルと感想は空白にできません。感想は２００文字までです'
    end

  end

  def destroy
    hon =Hon.find(params[:id])
    hon.destroy
    redirect_to hons_path, notice:'削除しました'
  end

  def about
  end

  def yuzas
    @yuzas = Yuza.all
    @yuza = current_yuza
  end

  def kansougun
    @hons = Hon.all
    @hon = Hon.new
    @yuza = current_yuza
  end

  private
    def hon_params
      params.require(:hon).permit(:title, :kansou)
    end
end

app/controllers/yuzas_controller.rb
class YuzasController < ApplicationController
  def show
    @yuza = Yuza.find(params[:id])
      @hons = @yuza.hons
      @hon = Hon.new
  end

  def edit
    @yuza = Yuza.find(params[:id])
      if @yuza != current_yuza
        redirect_to hons_path, notice:'＜error＞自分以外のマイページは編集することができません'      
      end
  end

  def update
    @yuza = Yuza.find(params[:id])
    if @yuza.update(yuza_params)
      redirect_to yuza_path(@yuza.id)
    else
      redirect_to yuza_path(@yuza.id), notice: '自己紹介は５０文字以内にしてください'
    end
  end

  private

  def yuza_params
    params.require(:yuza).permit(:name, :yuza_jikosyo, :yuza_gazou)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hons_helper.rb
module HonsHelper
end

app/helpers/yuzas_helper.rb
module YuzasHelper
end

app/views/hons/about.html.erb
<div class="about">
あばうと
</div>

app/views/hons/edit.html.erb
<h1>編集画面</h1>

<%= form_for(@hon) do |f| %>
       <p>タイトル</p> 
       <%= f.text_field :title %>

       <p>感想</p>
       <%= f.text_area :kansou %>

       <%= f.submit '編集完了' %>
<% end %>

app/views/hons/index.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-9">
            <div class="index-waku">
                <p><%= notice %></p>            

                <h1>Books</h1>
                <table border="1" class="ichiran">
                    <tr>
                        <th><b> タイトル </b></th>
                        <th><b> 感想 </b></th>
                        <th><b> 投稿者 </b></th>
                        <th colspan="3"></th>
                    </tr>
                    <% @hons.each do |hon| %>
                    <tr>
                        <td><%= hon.title %></td>
                        <td><%= simple_format(hon.kansou) %></td>
                        <td><%= hon.yuza.name %></td>
                        <td><%= link_to " show ", hon_path(hon.id) %></td>

                        <% if hon.yuza == current_yuza %>
                        <td><%= link_to " edit ", edit_hon_path(hon.id) %></td>
                        <td><%= link_to " destroy ", hon_path(hon.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
                        <% end %>

                    </tr>
                    <% end %>
                </table>
                
                <h2>New Book</h2>
                
                <div class="newbook">
                    <%= form_for(@hon) do |f| %>
                        <% if @hon.errors.any? %>
                            <div id="error_explanation">
                                <ul>
                                    <% @hon.errors.full_messages.each do |message| %>
                                      <li><%= message %></li>
                                    <% end %>
                                </ul>
                            </div>
                        <% end %>


                    <p>タイトル</p>
                    <%= f.text_field :title %>

                    <p>感想</p>
                    <%= f.text_area :kansou %>
                    <!-- 投稿ボタン -->
                    <br>
                    <button type="submit" class="btn btn-default">投稿</button>
                    <% end %>
                </div>
            </div>
        </div>

        <div class="col-lg-3">
            <div class="myinfo">
                <h3><span class="glyphicon glyphicon-user" aria-hidden="true"></span><%= @yuza.name %></h3>
                <%= attachment_image_tag @yuza, :yuza_gazou, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %><br>
                <%= link_to "マイページ", yuza_path(current_yuza.id) %>
            </div>
        </div>
    </div>
</div>

app/views/hons/kansougun.html.erb
<div class="container-fluid">
    <div class="col-lg-9">
        <div class="index-waku">
            <h1>本一覧</h1>
            <table border="1" class="ichiran">
                <tr>
                    <th><b>タイトル</b></th>
                    <th><b>感想</b></th>
                    <th colspan="3"></th>
                </tr>
                <% @hons.each do |hon| %>
                <tr>
                    <td><%= hon.title %></td>
                    <td><%= hon.kansou %></td>
                    <td><%= link_to "show", hon_path(hon.id) %></td>

                <% if hon.yuza == current_yuza %>
                    <td><%= link_to "edit", edit_hon_path(hon.id) %></td>
                    <td><%= link_to "destroy", hon_path(hon.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
                <% end %>

                </tr>
                <% end %>
            </table>
                 <h2>New Book</h2>
                
                <div class="newbook">
                    <%= form_for(@hon) do |f| %>

                    <p>タイトル</p>
                    <%= f.text_field :title %>

                    <p>感想</p>
                    <%= f.text_area :kansou %>
                    <!-- 投稿ボタン -->
                    <br>
                    <button type="submit" class="btn btn-default">投稿</button>
                    <% end %>
                </div>
        </div>
    </div>

    <div class="col-lg-3">
        <div class="myinfo">
            <h3><span class="glyphicon glyphicon-user" aria-hidden="true"></span><%= @yuza.name %></h3>
            <%= attachment_image_tag @yuza, :yuza_gazou, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %><br>
            <%= link_to "マイページ", yuza_path(current_yuza.id) %>
        </div>
    </div>
</div>

app/views/hons/show.html.erb
<%= notice %>

<div class="show-waku">
    <p><b>タイトル</b><%= @hon.title %></p>

    <p><b>感想</b><%= @hon.kansou %></p>


    <% if @hon.yuza == current_yuza %>
        <%= link_to "編集", edit_hon_path(@hon) %>
    <% end %>

    <%= link_to "戻る", hons_path %>
</div>

app/views/hons/top.html.erb
    <section class="top-waku">
        <h1>ようこそ<b>Bookers</b>へ！</h1>
        <p><b>Bookers</b>では、さまざまな書籍に関するあなたの意見や</p>
        <p>印象を共有し交換することができます</p>
        <a href="/hons">start</a>
    </section>

app/views/hons/yuzas.html.erb
<div class="container-fluid">
    <div class="col-lg-9">
        <div class="index-waku">
            <h1>ユーザー一覧</h1>
            <table border="1" class="ichiran">
                <tr>
                    <th><b>ユーザー名</b></th>
                    <th><b>自己紹介</b></th>
                    <th><b>ユーザーページを見る</b></th>
                </tr>
                    <% @yuzas.each do |yuza| %>
                <tr>
                    <td><%= yuza.name %></td>
                    <td><%= yuza.yuza_jikosyo %></td>
                    <td class="user-page-link"><%= link_to "◆◆click◆◆", yuza_path(yuza.id) %></td>
                    <% end %>
                </tr>
            </table>
        </div>
    </div>

    <div class="col-lg-3">
        <div class="myinfo">
            <h3><span class="glyphicon glyphicon-user" aria-hidden="true"></span><%= @yuza.name %></h3>
            <%= attachment_image_tag @yuza, :yuza_gazou, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %><br>
            <%= link_to "マイページ", yuza_path(current_yuza.id) %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <div class="header_waku clearfix container">
        <div class="header-name">
            <h1 class="bookers2">Bookers2</h1>
        </div>
        
        <% if yuza_signed_in? %>
          <nav class="link">
            <ul class="links">
                <li class="link_text"><span class="glyphicon glyphicon-home" aria-hidden="true"></span><%= link_to "ホーム", hons_path %></li>
                <li class="link_text"><span class="glyphicon glyphicon-user" aria-hidden="true"></span><%= link_to "User一覧", yuzas_path %></li>
                <li class="link_text"><span class="glyphicon glyphicon-book" aria-hidden="true"></span><%= link_to "Book一覧", kansougun_path %></li>
                <li class="link_text"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span><%= link_to "ログアウト", destroy_yuza_session_path, method: :delete %></li>
            </ul>
          </nav>
        <% else %>
          <nav class="link">
            <ul class="links">
                <li class="link_text"><span class="glyphicon glyphicon-home" aria-hidden="true"></span><%= link_to "トップ", root_path %></li>
                <li class="link_text"><span class="glyphicon glyphicon-file" aria-hidden="true"></span><%= link_to "アバウト", about_path  %></li>
                <li class="link_text"><span class="glyphicon glyphicon-check" aria-hidden="true"></span><%= link_to "新規会員登録", new_yuza_registration_path %></li>
                <li class="link_text"><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span><%= link_to "ログイン", new_yuza_session_path %></li>
            </ul>
          </nav>
        <% end %>
        
    </div>
</header>
    <%= yield %>
  </body>
</html>

app/views/yuzas/edit.html.erb
<h2>ユーザー情報編集</h2>

<%= form_for(@yuza) do |f| %>
        <label>名前</label><br>
        <%= f.text_field :name, autofocus: true %>
<br>
        <label>自己紹介</label><br>
        <%= f.text_field :yuza_jikosyo, placeholder:"最大50文字" %>
<br>
        <label>プロフィール画像</label><br>
        <%= f.attachment_field :yuza_gazou, placeholder:"画像を貼り付け" %>
<br>
        <%= f.submit "変更を保存" %>
<% end %>
  

app/views/yuzas/show.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-9">
            <div class="index-waku">
                <p><%= notice %></p>

                <h1>Books</h1>
                <table border="1" class="ichiran">
                    <tr>
                        <th><b>タイトル</b></th>
                        <th><b>感想</b></th>
                        <th colspan="3"></th>
                    </tr>
                    <% @hons.each do |hon| %>
                    <tr>
                        <td><%= hon.title %></td>
                        <td><%= hon.kansou %></td>
                        <td><%= link_to "show", hon_path(hon.id) %></td>

                    <% if hon.yuza == current_yuza %>
                        <td><%= link_to "edit", edit_hon_path(hon.id) %></td>
                        <td><%= link_to "destroy", hon_path(hon.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
                    <% end %>

                    </tr>
                    <% end %>
                </table>
                <h2>New Book</h2>
                <div class="newbook">
                <%= form_for(@hon) do |f| %>

                <p>タイトル</p>
                <%= f.text_field :title %>

                <p>感想</p>
                <%= f.text_area :kansou %>
                <!-- 投稿ボタン -->
                <br>
                <button type="submit" class="btn btn-default">投稿</button>
                <% end %>
                </div>

            </div>
        </div>

        <div class="col-lg-3">
            <div class="myinfo">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span><h3><%= @yuza.name %></h3>
                <%= attachment_image_tag @yuza, :yuza_gazou, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %><br>
                <%= @yuza.yuza_jikosyo %><br>
                <% if @yuza == current_yuza %>
                    <%= link_to "マイページ編集", edit_yuza_path(current_yuza.id) %>
                <% end %>
            </div>
        </div>
    </div>
</div>